<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'BoldMinded\\Carson\\Dependency\\DateError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateError.php',
    'BoldMinded\\Carson\\Dependency\\DateException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateException.php',
    'BoldMinded\\Carson\\Dependency\\DateInvalidOperationException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateInvalidOperationException.php',
    'BoldMinded\\Carson\\Dependency\\DateInvalidTimeZoneException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateInvalidTimeZoneException.php',
    'BoldMinded\\Carson\\Dependency\\DateMalformedIntervalStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedIntervalStringException.php',
    'BoldMinded\\Carson\\Dependency\\DateMalformedPeriodStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedPeriodStringException.php',
    'BoldMinded\\Carson\\Dependency\\DateMalformedStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedStringException.php',
    'BoldMinded\\Carson\\Dependency\\DateObjectError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateObjectError.php',
    'BoldMinded\\Carson\\Dependency\\DateRangeError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateRangeError.php',
    'BoldMinded\\Carson\\Dependency\\Override' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/Override.php',
    'BoldMinded\\Carson\\Dependency\\SQLite3Exception' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/SQLite3Exception.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
