<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'BoldMinded\\Carson\\Dependency\\Symfony\\Polyfill\\Php83\\' => array($vendorDir . '/symfony/polyfill-php83'),
    'BoldMinded\\Carson\\Dependency\\Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'BoldMinded\\Carson\\Dependency\\Symfony\\Contracts\\HttpClient\\' => array($vendorDir . '/symfony/http-client-contracts'),
    'BoldMinded\\Carson\\Dependency\\Symfony\\Component\\HttpClient\\' => array($vendorDir . '/symfony/http-client'),
    'BoldMinded\\Carson\\Dependency\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'BoldMinded\\Carson\\Dependency\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'BoldMinded\\Carson\\Dependency\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'BoldMinded\\Carson\\Dependency\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'BoldMinded\\Carson\\Dependency\\OpenAI\\' => array($vendorDir . '/openai-php/client/src'),
    'BoldMinded\\Carson\\Dependency\\Nyholm\\Psr7\\' => array($vendorDir . '/nyholm/psr7/src'),
    'BoldMinded\\Carson\\Dependency\\Litzinger\\Basee\\' => array($vendorDir . '/litzinger/basee/src'),
    'BoldMinded\\Carson\\Dependency\\Http\\Message\\MultipartStream\\' => array($vendorDir . '/php-http/multipart-stream-builder/src'),
    'BoldMinded\\Carson\\Dependency\\Http\\Discovery\\' => array($vendorDir . '/php-http/discovery/src'),
    'BoldMinded\\Carson\\Dependency\\Bamarni\\Composer\\Bin\\' => array($vendorDir . '/bamarni/composer-bin-plugin/src'),
    'BoldMinded\\Carson\\' => array($baseDir . '/addons/carson'),
);
