<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit263c6fbb7fad07ac577608aaaa2fa85d
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '662a729f963d39afe703c9d9b7ab4a8c' => __DIR__ . '/..' . '/symfony/polyfill-php83/bootstrap.php',
        '61ba3e92ef91a7a0f1cc260ebd9290e4' => __DIR__ . '/..' . '/openai-php/client/src/OpenAI.php',
    );

    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BoldMinded\\Carson\\Dependency\\Symfony\\Polyfill\\Php83\\' => 52,
            'BoldMinded\\Carson\\Dependency\\Symfony\\Contracts\\Service\\' => 55,
            'BoldMinded\\Carson\\Dependency\\Symfony\\Contracts\\HttpClient\\' => 58,
            'BoldMinded\\Carson\\Dependency\\Symfony\\Component\\HttpClient\\' => 58,
            'BoldMinded\\Carson\\Dependency\\Psr\\Log\\' => 37,
            'BoldMinded\\Carson\\Dependency\\Psr\\Http\\Message\\' => 46,
            'BoldMinded\\Carson\\Dependency\\Psr\\Http\\Client\\' => 45,
            'BoldMinded\\Carson\\Dependency\\Psr\\Container\\' => 43,
            'BoldMinded\\Carson\\Dependency\\OpenAI\\' => 36,
            'BoldMinded\\Carson\\Dependency\\Nyholm\\Psr7\\' => 41,
            'BoldMinded\\Carson\\Dependency\\Litzinger\\Basee\\' => 45,
            'BoldMinded\\Carson\\Dependency\\Http\\Message\\MultipartStream\\' => 58,
            'BoldMinded\\Carson\\Dependency\\Http\\Discovery\\' => 44,
            'BoldMinded\\Carson\\Dependency\\Bamarni\\Composer\\Bin\\' => 50,
            'BoldMinded\\Carson\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BoldMinded\\Carson\\Dependency\\Symfony\\Polyfill\\Php83\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php83',
        ),
        'BoldMinded\\Carson\\Dependency\\Symfony\\Contracts\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'BoldMinded\\Carson\\Dependency\\Symfony\\Contracts\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client-contracts',
        ),
        'BoldMinded\\Carson\\Dependency\\Symfony\\Component\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client',
        ),
        'BoldMinded\\Carson\\Dependency\\Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Psr\\Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-client/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'BoldMinded\\Carson\\Dependency\\OpenAI\\' => 
        array (
            0 => __DIR__ . '/..' . '/openai-php/client/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Nyholm\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/nyholm/psr7/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Litzinger\\Basee\\' => 
        array (
            0 => __DIR__ . '/..' . '/litzinger/basee/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Http\\Message\\MultipartStream\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-http/multipart-stream-builder/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Http\\Discovery\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-http/discovery/src',
        ),
        'BoldMinded\\Carson\\Dependency\\Bamarni\\Composer\\Bin\\' => 
        array (
            0 => __DIR__ . '/..' . '/bamarni/composer-bin-plugin/src',
        ),
        'BoldMinded\\Carson\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/addons/carson',
        ),
    );

    public static $classMap = array (
        'BoldMinded\\Carson\\Dependency\\DateError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateError.php',
        'BoldMinded\\Carson\\Dependency\\DateException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateException.php',
        'BoldMinded\\Carson\\Dependency\\DateInvalidOperationException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidOperationException.php',
        'BoldMinded\\Carson\\Dependency\\DateInvalidTimeZoneException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidTimeZoneException.php',
        'BoldMinded\\Carson\\Dependency\\DateMalformedIntervalStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedIntervalStringException.php',
        'BoldMinded\\Carson\\Dependency\\DateMalformedPeriodStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedPeriodStringException.php',
        'BoldMinded\\Carson\\Dependency\\DateMalformedStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedStringException.php',
        'BoldMinded\\Carson\\Dependency\\DateObjectError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateObjectError.php',
        'BoldMinded\\Carson\\Dependency\\DateRangeError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateRangeError.php',
        'BoldMinded\\Carson\\Dependency\\Override' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/Override.php',
        'BoldMinded\\Carson\\Dependency\\SQLite3Exception' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/SQLite3Exception.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit263c6fbb7fad07ac577608aaaa2fa85d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit263c6fbb7fad07ac577608aaaa2fa85d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit263c6fbb7fad07ac577608aaaa2fa85d::$classMap;

        }, null, ClassLoader::class);
    }
}
